server:
    port: 8088
spring:
    devtools:
        enabled: true
    http:
        encoding:
          charset: UTF-8
          force: true
          enabled: true
        multipart:
          location: E:\temp\images
    freemarker:
        template-loader-path:
        - classpath:/templates
        - file:./templates
        cache: false
        checkTemplateLocation: false
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/db_mblog?useSSL=false&characterEncoding=utf8
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource

    jpa:
        database: mysql
        show-sql: false
        # 更新或者创建
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.store.root}/indexes

    servlet:
        multipart:
            max-file-size: 5MB

    mail:
        host: smp.mton.com
        username: 123@163.com
        password: 123456
        port: 25
        properties:
            mail.smtp.auth: true
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: mblog.nblog.entity # 注意：对应实体类的路径
logging:
  level:
     mblog.nblog.mapper : debug
# site.theme: [default|card]
site:
    theme: card
    store:
      root: /data/mblog/
      size: 2
      repo: relative